python_sources = files(
    '__init__.py',
    '__main__.py',
    'app.py',
    'args.py'
    'config.py',
    'main.py',
    'state.py'
)

py.install_sources(
    python_sources,
    subdir: 'frxxv',
    install_tag: 'runtime'
)

subdir('assets')
subdir('controllers')
subdir('ingest')
subdir('pcolormesh')
subdir('plotting')
subdir('shell')
subdir('widgets')
subdir('windows')
