python_sources = files(
    '__init__.py',
    'edit_manager.py',
    'file_manager.py',
    'interaction_manager.py',
    'key_router.py',
    'mask_controller.py',
    'panel_lims_controller.py',
    'plot_controller.py',
    'product_manager.py'
)

py.install_sources(
    python_sources,
    subdir: 'frxxv/controllers',
    install_tag: 'runtime'
)
